import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import NextTopLoader from 'nextjs-toploader';
import BottomBar from "@/components/BottomBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop-24",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className + "bg-[#181818]  mx-auto  2xl:px-8 lg:px-4 px-2"}>
        <NextTopLoader
          color="#000AFF"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #000AFF,0 0 5px #000AFF"
          zIndex={1600}
          showAtBottom={false}
        />
        <Header />

        {children}
        <BottomBar />
        <Footer />
      </body>
    </html>
  );
}
